### PR TITLE
Support Linux

### PR DESCRIPTION
**Pull request by ykyouhei**
Add import Dispatch

### CODE REVIEW

**Comment by s4cha** [comment]
@ykyouhei This is great! Do we need `import Dispatch` in Helpers.swift as well? since it calls dispatch methods.

**Comment by ykyouhei** [comment]
@s4cha 
Thank you for merging the pull request!
When using it with Bluemix and Swift Package Manager, no build error occurred. However, I think `import Dispatch`  is necessary when running test code on Linux.

**Comment by s4cha** [comment]
@ykyouhei Thank You for contributing :)
So you're using then on a server ? That's awesome !!
I will add the other dispatch and bump the version number tomorrow ;)

**Comment by ykyouhei** [comment]
@s4cha 
Thanks!
>So you're using then on a server ? 

yes! We implemented server side swift using Bluemix × [Kitura](https://github.com/IBM-Swift/Kitura)!

**Pull request merged**
