### PR TITLE
Resolve compile issue on Xcode 9.3

### LINKED ISSUE #37: thenPromise is not building with XCode 9.3 beta
VoidPromise.swift:32
Cannot convert value of type '(Void) -> ()' to expected argument type '() -> Void'

XCode version: 9.3 beta (9Q98q)

### PR DESCRIPTION
**Pull request by casademora**
The swift compiler was unable to resolve the overloaded convenience initializer. Being more explicit by marking the desired initializer with `void:` allows the compiler to successfully complete it's build. Resolves #37

### CODE REVIEW

**Comment by s4cha** [comment]
@casademora Thanks a ton for taking the time to update for the latest version!
I have a suggestion on the code.
Why not using the following to desambiguate the signature : 

```swift
extension Promises {
    public static func delay(_ time: TimeInterval) -> Promise<Void> {
        return Promise { (resolve: @escaping (() -> Void), _: @escaping ((Error) -> Void)) in
            callBackOnCallingQueueIn(time: time, block: resolve)
        }
    }
}
```

It has the same effect without having to modify the initializer itself.
What do you think?

Cheers,

**Comment by casademora** [comment]
Awesome, if that works, then let's go with that 👍 I'll update this request accordingly...

**Comment by s4cha** [comment]
Actually it worked before I launched the unit tests...

**Comment by s4cha** [comment]
Looks like we have two options here 

1 - is the solution you suggested.
```swift
func upload() -> Promise<Void> {
    return Promise(void: { resolve, _, progress in
         resolve()
    })
}
```
That would make the clients have to use the `void:` prefix, and have to add the parenthesis as well.

2 - The other solution would be to get rid of the `VoidPromise` file altogether.
This makes it compile but now we'd have to call `resolve(())` instead of `resolve()` inside void promise initialisers, which is not ideal neither.

Both would introduce breaking changes on the user's part, which is obviously something we want to avoid as much as possible :/

I hope we're going to find a third solution !

**Comment by s4cha** [comment]
Having the users deambiguate on their side would be far form ideal as well :
```swift
func upload() -> Promise<Void> {
    return Promise { (resolve: @escaping () -> Void, _, progress) in
        resolve()
    }
}
```

**Comment by s4cha** [comment]
Do unit tests work without code changes on your side?

**Comment by casademora** [comment]
I've fixed the unit tests to use the disambiguation syntax. I think while not ideal, this is the better solution at the moment. It's certainly better than making a `void:` overload of the initializer. :)

**Comment by s4cha** [comment]
Thanks @casademora, I agree. Let's merge this to have a working version on the new Xcode and see 
if we come up with a solution later.
This is going to be a very big breaking change for the api users though.
I'll have a try on the project I'm working on to see how things go.

Cheers!

**Comment by antonm76** [comment]
@s4cha Hi! Are you going to update a .podspec file? Do you want me to create a pull request?

**Comment by ztepsa** [comment]
Hi @s4cha! Question about when you plan to release new GitHub version with this fix? Would be great to have it soon so that CocoaPods and Carthage integration can work without using the `master` branch.

**Comment by s4cha** [comment]
@antonm76 This wasn't released on purpose just so that we run test on our app to assess how much breaking changes we have on the client side.

@ztepsa in the meantime (at leat with Carthage) you can use : 
github "freshos/then" "a210c56655d64d8e6cb06ca4f13a67b2a9ca36ce"
and then run `carthage update then  --no-use-binaries` so that it compiles it with your local version of Xcode, ignoring the prepackaged .fmk file.

**Comment by antonm76** [comment]
@s4cha I see your point, but there are 18,585 downloads of thenPromise pod and 556 installations. Do you want all of users to reference GitHub repository directly? If I was you I would release an urgent update first and then start thinking about better solution, no offense.

**Comment by ztepsa** [comment]
I also agree with point stated above, referencing master branch or specific commit is really not a solution I'd like to do. I am using `master` so that development can continue, but for releasing new version of the SDK that depends on this library I would only go with tagged release. That's why I asked when do you plan on releasing a new version.

**Comment by s4cha** [comment]
Ok guys, you definitely have a point, I'm on it :)

**Comment by s4cha** [comment]
@casademora @ztepsa @antonm76  `4.0.0` is out with swift 4.1 : 
https://github.com/freshOS/then/releases/tag/4.0.0

Thanks a ton for your help and patience :)

@casademora I just invited you as a gold contributor which will give you write access the the repo 🏅 
Of course we'll still use PRs but you won't have to use a fork anymore 👍

**Comment by antonm76** [comment]
@s4cha great! Thank you, man!

**Comment by ztepsa** [comment]
@s4cha Great work, thanks all for fast update!

**Comment by casademora** [comment]
@s4cha great, thanks!

**Pull request merged**
