### PR TITLE
Fix thread race

### PR DESCRIPTION
**Pull request by cfanfs**
Fix issue #39

### CODE REVIEW

**Comment by cfanfs** [comment]
As you can see, the operation on `state` and `blocks` of a Promise should be atomic, for example:
```
if state == ... {
  // do something with blocks
}
```
protecting `state` and `blocks` independently will cause following problems:
```
Thread 1: ---- [if state == ... is true ]--------------------------[do something with blocks]----
Thread 2: ----------------------------------[update state]-----------------------------------
```
and that will lead to incorrect result.

**Comment by cfanfs** [comment]
Hi All

I'm submitting a lot of things here. Sorry for not able to provide more details now.
I really hope that this pull request does not violate your code styling and design, and I am looking forward to see your response. Thank you!

**Comment by s4cha** [comment]
@cfanfs First of all please excuse the late reply, I've been pretty busy working on https://github.com/Yummypets/YPImagePicker lately 🤓 
Thank you so much for taking the time to try to solve your own issue, this is very appreciated :)
I went through the code and it looks good to me. I'd love if you could sum up the approach taken here.
I guess it's about always accessing the state from the same queue but I'd love to hear your thoughts.
I'm going to test this in our App to make sure everything works as expected and will get back to you 👍

**Comment by s4cha** [comment]
@cfanfs I've played around with it in our App and so far so good, seems like everything still works as expected. Plus all tests pass so 👌

**Comment by cfanfs** [comment]
@s4cha Thanks for your reply :-)

This pull request is trying to solve two problems below: 

#### Thread Race in whenAll
As it was mentioned in issue #39, the test case `testWhenAllAllAsynchronous` will lead to a crash, which is caused by writing stack variable `ts: [T]` on different thread at the same time. Locking `ts` will solve this problem.

#### Atomic Operation
After fixing the first issue, the test case `testWhenAllAllAsynchronous` still fails randomly. By adding some logs, I noticed that some of the `finally` blocks after the input promises are not called.  The logs are
``` swift 
// Promise.swift

internal func syncStateWithCallBacks(success: @escaping ((T) -> Void),
                                     failure: @escaping ((Error) -> Void),
                                     progress: @escaping ((Float) -> Void)) {
    let reference = Unmanaged.passUnretained(self).toOpaque().debugDescription
    print("\(reference): State before switch: \(state)")
    switch state {
    case let .fulfilled(value):
        print("\(reference): Already fulfilled")
        success(value)
    case let .rejected(error):
        failure(error)
    case .dormant, .pending:
        print("\(reference): Will update blocks, current state is \(state)")
        blocks.success.append {
            success($0)
            print("\(reference): Success")
        }
        blocks.fail.append(failure)
        blocks.progress.append(progress)
    }
    print("\(reference): State after switch: \(state)")
}

```
and when the test fails, I can get console output containing the following piece
```
0x00007fcd27e0bad0: State before switch: pending(0.0)
0x00007fcd27e0bad0: Will update blocks, current state is fulfilled()
0x00007fcd27e0bad0: State after switch: fulfilled()
```
from which we can see that Promise `0x00007fcd27e0bad0` didn't execute its newly appended `success` block(expected "0x00007fcd27e0bad0: Success" does not exist in console), because its state has already been changed to `fulfilled` on another thread before the block is added.

The point is, `state` and `blocks` of Promise are related properties in this design, so operations like **"check the state then handle the blocks"** should be atomic. `initialPromiseStart`, `initialPromiseStarted` and `promiseProgressCallBack` are also not independent properties, and the operations on them need to be atomic, too.

My idea of fixing this is
- Protect(lock) the public and internal interfaces in *Promise.swift*, since you don't know on which thread it would be called.
- Provide some thread-unsafe private functions, and requires these functions to be called on lockQueue.
- Stored blocks of Promise (`threadUnsafeBlocks`,  `initialPromiseStart`, `promiseProgressCallBack`) should be read/copied/updated on lockQueue, but SHOULD NOT be executed on lockQueue, because doing this will cause deadlock. 

I hope it is clear enough to explain my pull request.

Thank you!

**Comment by s4cha** [comment]
@cfanfs This is a very clear explanation and very good work!
On a side note I just invited you as a freshOS Gold Contributor (I recognise great work when I see it !)
Like this you'll be able to have write access to the repo :)

Thank you so much for your time and efforts 🙏

**Comment by cfanfs** [comment]
@s4cha glad to join freshOS :) You're doing great job here.
I have to say that I really have little time on open source contribution. :/ Hope to get more time in the future.

**Pull request merged**
